# Cryptic immunogenicity prediction example.
path:
  input_csv: "mimicneoai/example/immunogenicity_prediction/input/input_peptide_hla.csv"
  output_csv: "mimicneoai/example/immunogenicity_prediction/output/cryptic_predictions.csv"
  hla_source: "netmhc-pseudoseq"

args:
  batch_size: 512
  num_processes: 1
  verbose: true
  include_input_qc: true
  device: "cuda"

io:
  peptide_col: "peptide"
  hla_col: "hla"
  score_col: "immunogenicity_score"
