# input_dir/
# ├── Sample_001/
# │   ├── Sample_001.R1.fq.gz
# │   └── Sample_001.R2.fq.gz
# ├── Sample_002/
# │   ├── Sample_002.R1.fq.gz
# │   └── Sample_002.R2.fq.gz
# └── Sample_003/
#     ├── Sample_003.R1.fq.gz
#     └── Sample_003.R2.fq.gz
# Configuration Paths
path:
  tmp_dir: "/path/to/project/tmp/"          # Directory for temporary files
  input_dir: "/path/to/raw_data/"           # Input data directory containing samples
  output_dir: "/path/to/analysis_results/" # Output directory for final results

# Runtime Parameters
args:
  thread: 30                # CPU threads per sample
  hla_binding_threads : 5 # Number of threads for parallel pvactools runs; too many may reduce efficiency—adjust based on server performance.
  pool_size: 1              # Concurrent sample processing count
  mem: "128G"               # Max memory per sample (pool_size × mem < total memory)

# Analysis Parameters
others:
  seq_type: "wes"           # Sequencing type (wes/rna)
  species: "human"          # Species (human/mouse)
  pair: True                # Paired-end sequencing (True/False)
  QC: True                  # Enable quality control

  tumor_with_matched_normal: True   # In this mode, input samples must be provided as a matched Tumor-Normal pair.
                                   # Use a comma to separate sample names, e.g. - {TumorName},{NormalName}
  host_variants_calling_and_annotation: True  # Host variant processing
  mutation_calling_tool: "Mutect2"  # Variant caller (Mutect2 for somatic variants)
  hlatyping: False          # HLA typing enable
  peptides_identification_and_binding_prediction: False  # Peptide prediction
  
  # WES-specific parameters
  bed_file: "/path/to/target_regions/exome_targets.bed"  # Capture regions file

  # Algorithms for pVACbind (space-separated)
  algo: "BigMHC_EL BigMHC_IM DeepImmuno MHCflurry MHCflurryEL MHCnuggetsI MHCnuggetsII NNalign NetMHC NetMHCIIpan NetMHCIIpanEL NetMHCpan NetMHCpanEL PickPocket SMM SMMPMBEC"

# Sample List (Example entries)
samples:
  - Sample_001_T,Sample_001_N
  - Sample_002_T,Sample_002_N